Coverage Targets Whitespace
intersystems/TestCoverage pull request #41
Opened 2024-07-12 19:28 UTC by isc-cge

Now ignores leading and trailing whitespace for file names in coverage.list

2024-07-12 19:44 UTC, isc-tleavitt requested changes
Big picture notes:
It would be great to make GetCoverageTargetsForFile non-private and add a unit test for it (codecov is flagging on that - let's permit it to!)
We should only bump versions when we actually release, not for every single change. Let's go back to 3.1.1 and put this under the "fixed" section for that version.

2024-07-15 14:19 UTC, isc-shuliu commented on CHANGELOG.md
> +- Now the code strips leading and trailing whitespace from coverage.list, so "PackageName.PKG " will still be loaded properly
Would be good to reference the PR number #41 here

2024-07-15 14:25 UTC, isc-shuliu approved these changes

2024-07-29 14:21 UTC, isc-tleavitt approved these changes

2024-07-29 14:21 UTC, merged